### ISSUE TITLE
Writing to VTX is broken

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2279] opened 2022-07-21 15:03 UTC
This issue is the twin of #2277 . VTX files created by dolfinx [C++ interface in my case] make Paraview crash. Curiously, in my case bp files still work fine. I verified that the regression was introduced in #2272 .

**Comment by garth-wells** [comment] 2022-07-21 17:19
Duplicate of https://github.com/FEniCS/dolfinx/issues/2277.

**Closed by garth-wells** 2022-07-21 17:19 UTC
