### ISSUE TITLE
Move 'function' namespace/module into `fem`

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#1191] opened 2020-10-30 10:37 UTC
Move `function::` classes and functions to `fem::` from C++, and similarly for Python.

The `function` namespace presently has few classes and methods, and `fem.Function` is more informative that `function.Function`.

**Comment by michalhabera** [comment] 2020-11-03 21:10
Duplicate of #1183

**Closed by michalhabera** 2020-11-03 21:10 UTC
Labels: proposal
