### ISSUE TITLE
[BUG]: `nympy.can_cast` issue in `dolfinx/mesh.py` with numpy 2.0.2

### ISSUE THREAD

**Issue by cmaurini** [FEniCS/dolfinx#3456] opened 2024-10-06 10:06 UTC
### Summarize the issue

Issue with `numpy.can_cast` with numpy version 2.0.2 (working correctly with 2.1.0) triggered in `dolfinx.mesh.py:486` 

### How to reproduce the bug

Run the code below to see where the problem is triggered in `dolfinx`. But the true minimal example is 
```import numpy as np; np.can_cast(1, np.int32)```

### Minimal Example (Python)

```Python
import dolfinx
from mpi4py import MPI
domain = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 2, 2)
boundary_facets = dolfinx.mesh.locate_entities_boundary(domain, 1, lambda x : x[0] > -1)
mt = dolfinx.mesh.meshtags(domain, 1, boundary_facets, 1)
```

### Output (Python)

```bash
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File /Users/maurini/Documents/codes/fenicsx-fracture/notebooks/linear-elasticity/test.py:6
      4 domain = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 2, 2)
      5 boundary_facets = dolfinx.mesh.locate_entities_boundary(domain, 1, lambda x : x[0] > -1)
----> 6 mt = dolfinx.mesh.meshtags(domain, 1, boundary_facets, 1)
      7 #mt = mesh.meshtags(
      8 #    msh, 1, top_facets, np.full_like(top_facets, 1, dtype=np.int32)
      9 #)

File ~/miniconda3/envs/fenicsx-fracture/lib/python3.12/site-packages/dolfinx/mesh.py:486, in meshtags(mesh, dim, entities, values)
    466 """Create a MeshTags object that associates data with a subset of mesh entities.
    467 
    468 Args:
   (...)
    482 
    483 """
    485 if isinstance(values, int):
--> 486     assert np.can_cast(values, np.int32)
    487     values = np.full(entities.shape, values, dtype=np.int32)
    488 elif isinstance(values, float):

TypeError: can_cast() does not support Python ints, floats, and complex because the result used to depend on the value.
This change was part of adopting NEP 50, we may explicitly allow them again in the future.
```

### Version

0.8.0

### Installation

I installed using conda, I am on `Darwin CMMacBookPro-2.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64`. 

But the issue should be due only to the numpy version.

**Comment by cmaurini** [comment] 2024-10-06 10:24
As an update, after further testing I got the error in another environment also pinning numpy to 2.1.0

Below is my env file
```
name: fenicsx-fracture
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx==0.8.0
  - matplotlib
 # - numba
  - numpy==2.1.0
  - sympy
  - scipy
  - pip
  - gmsh
  - python-gmsh
  - pythreejs
  - jupyter-book
  - autopep8
  - black
  - flake8
  - autoflake
  - pyaml
  - pandas
  - jupyterlab
  - pip
  - pyvista
  - ipygany
  - jupytext
  - ipyparallel
```

**Comment by garth-wells** [comment] 2024-10-07 20:50
I can't reproduce.

**Comment by cmaurini** [comment] 2024-10-08 05:39
Strange, because a colleague of mine with a clean installation on a macbook with apple silicon get the same error. This is the one-liner  to reproduce:

```
conda create --yes -n test numpy; conda activate test;  python -c "import numpy as np; print('numpy version', np.__version__); np.can_cast(1, np.int32)"
```
It gives me as output:
```
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/maurini/miniconda3/envs/test

  added / updated specs:
    - numpy


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h99b78c6_7 
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2024.8.30-hf0a4a13_0 
  libblas            conda-forge/osx-arm64::libblas-3.9.0-24_osxarm64_openblas 
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-24_osxarm64_openblas 
  libcxx             conda-forge/osx-arm64::libcxx-19.1.1-ha82da77_0 
  libexpat           conda-forge/osx-arm64::libexpat-2.6.3-hf9b8971_0 
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5 
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-13_2_0_hd922786_3 
  libgfortran5       conda-forge/osx-arm64::libgfortran5-13.2.0-hf226fd6_3 
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-24_osxarm64_openblas 
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.27-openmp_h517c56d_1 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.46.1-hc14010f_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.3.1-h8359307_2 
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-19.1.0-hba312e6_0 
  ncurses            conda-forge/osx-arm64::ncurses-6.5-h7bae524_1 
  numpy              conda-forge/osx-arm64::numpy-2.1.2-py312h801f5e3_0 
  openssl            conda-forge/osx-arm64::openssl-3.3.2-h8359307_0 
  pip                conda-forge/noarch::pip-24.2-pyh8b19718_1 
  python             conda-forge/osx-arm64::python-3.12.7-h739c21a_0_cpython 
  python_abi         conda-forge/osx-arm64::python_abi-3.12-5_cp312 
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1 
  setuptools         conda-forge/noarch::setuptools-75.1.0-pyhd8ed1ab_0 
  tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1 
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0 
  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0 



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

numpy version 2.1.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: can_cast() does not support Python ints, floats, and complex because the result used to depend on the value.
This change was part of adopting NEP 50, we may explicitly allow them again in the future.
```

and 

```
(test) test|⇒ uname -a
Darwin CMMacBookPro-2.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64
```

That said, there is a easy workaround (thanks @jorgensd):
`mt = mesh.meshtags(msh, 1, top_facets, np.full_like(top_facets, 1, dtype=np.int32))`

**Comment by jhale** [comment] 2024-10-08 05:42
DOLFINx `v0.8.0` was released before numpy `2.0.0` - I think we had some numpy 2.x related linting at this time, but not continuous integration.

https://numpy.org/doc/stable/release/2.0.0-notes.html

So it is not surprising there are some issues if you pin.

**Comment by garth-wells** [comment] 2024-10-08 11:34
> I can't reproduce.

Sorry, I checked NumPy versions but not DOLFINx versions. Following @jhale comment, issues must be fixed in development version. v0.9 release should be coming very soon.

**Comment by garth-wells** [comment] 2024-10-15 04:31
Closing because v0.9 is now out, with support for NumPy v2.

**Closed by garth-wells** 2024-10-15 04:31 UTC
Labels: bug
