### ISSUE TITLE
[BUG]: Newton solver iterations when residual is NAN 

### ISSUE THREAD

**Issue by phkonzen** [FEniCS/dolfinx#2524] opened 2023-02-08 17:18 UTC
### How to reproduce the bug

When the residual of the nonlinear problem is `nan` (not-a-number), I would expect that the solver stops iterating. Keeping the newton iterations may provoque error in the PETSc external library and the `newtonsolver` option `error_on_nonconvergence = False` will be of no help.

### Output (Python)

```bash
* It follows the LOG

NewtonSolver.cpp:36    INFO| Newton iteration 1: r (abs) = -nan (tol = 1e-10) r (rel) = -nan(tol = 1e-09)
petsc.cpp:677   INFO| PETSc Krylov solver starting to solve system.
NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = -nan (tol = 1e-10) r (rel) = -nan(tol = 1e-09)
petsc.cpp:677   INFO| PETSc Krylov solver starting to solve system.
loguru.cpp:526   INFO| atexit

* Terminal output

Traceback (most recent call last):
  File "/home/u/solver.py", line 130, in <module>
    # solve problem
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfinx/nls/petsc.py", line 41, in solve
Traceback (most recent call last):
  File "/home/pkonzen/GitLab/solow-swan/codes/python/2d/solver.py", line 130, in <module>
    n, converged = super().solve(u.vector)
RuntimeError: Failed to successfully call PETSc function 'KSPSolve'. PETSc error code is: 76, Error in external library
```

### Version

0.5.1

**Comment by francesco-ballarin** [comment] 2023-10-08 05:42
It does not seem that anyone is looking into this, and I do not expect this will be given a high priority in the future, so I'll be closing this. If this were to change, feel free to reopen.

In my experience, getting NaNs stems from two cases:
- you set a blatantly wrong initial guess, e.g. an initial guess equal to zero when the residual contains a term 1 / solution. Better handling of NaN wouldn't help you much, since you'd still be on your own in understanding what is the cause of the problem.
- the NaN appears after a few iterations, because the solver is diverging, and you may want to catch that the case e.g. to retry again with a different initial guess. In that case, you may consider using a try/except.

**Closed by francesco-ballarin** 2023-10-08 05:42 UTC
Labels: bug
