### ISSUE TITLE
[BUG]: Log Level Info seems to freeze bb_tree in Jupyter notebook

### ISSUE THREAD

**Issue by jorgenin** [FEniCS/dolfinx#2768] opened 2023-09-11 18:55 UTC
### How to reproduce the bug

Setting log level to info causes a juptyer notebook script to hang if creating a bb_tree.

I want to also add that this is just on ipynb files. I believe .py files work well. I believe the issue is that the bb_tree is outputting a lot of info text causing the juptyer notebook to be overwhelmed and freeze.

### Minimal Example (Python)

```Python
import numpy as np
from mpi4py import MPI
from petsc4py import PETSc
from dolfinx import mesh, fem, log
import ufl

N=100

domain = mesh.create_rectangle(MPI.COMM_WORLD,[[-20,-20],[20,0]],[N,int(N*20/40)],cell_type=mesh.CellType.triangle)

from dolfinx import geometry
bb_tree = geometry.bb_tree(domain, domain.topology.dim) #THIS WORKS FINE

log.set_log_level(log.LogLevel.INFO)
bb_tree = geometry.bb_tree(domain, domain.topology.dim)#THIS DOESN'T WORK
```

### Version

main branch

### Installation

Installed on MAC OS built on M1 processor

**Comment by francesco-ballarin** [comment] 2023-10-15 13:59
Hi @jorgenin ,
please have a look at this test notebook [test1.ipynb.txt](https://github.com/FEniCS/dolfinx/files/12909736/test1.ipynb.txt) (upon renaming it to `.ipynb`), which reproduces your error in a much simpler setting.

The last cell contains a call to a function which:
* in the second line in the cell (currently commented out), produces 48K of output to `stderr`,
* in the third line in the cell, produces 107K of output to `stderr`.

The second line succedes inside a `jupyter lab` session, while the third one fails as for you.

I suggest that you use this notebook to open an issue in the `jupyter lab` github repository, because the limit of 100K is suspiciously close to https://github.com/jupyterlab/jupyterlab/issues/12845.

Overall, this is not a `dolfinx` bug, and (short of dropping the log entries) there is nothing we can do on our end. Hence, I am closing this.

**Closed by francesco-ballarin** 2023-10-15 13:59 UTC
Labels: bug
