### ISSUE TITLE
TensorFunctionSpace is broken

### ISSUE THREAD

**Issue by atouminet** [FEniCS/dolfinx#2324] opened 2022-08-17 12:36 UTC
Creating a tensor function space with `len(shape) > 2` fails.

MWE
```python
import dolfinx.fem, dolfinx.mesh
from mpi4py import MPI

mesh = dolfinx.mesh.create_unit_square(MPI.COMM_SELF, 3, 3)
V = dolfinx.fem.TensorFunctionSpace(mesh, ("DG", 0), shape=(2, 2, 2, 2))
```

Error message:
```shell
Traceback (most recent call last):
  File "/home/armand/s/mwe/mwe.py", line 5, in <module>
    V = dolfinx.fem.TensorFunctionSpace(mesh, ("DG", 0), (2, 2, 2, 2))
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/dolfinx/fem/function.py", line 582, in TensorFunctionSpace
    return FunctionSpace(mesh, ufl_element)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/dolfinx/fem/function.py", line 457, in __init__
    (self._ufcx_element, self._ufcx_dofmap), module, code = jit.ffcx_jit(
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/dolfinx/jit.py", line 56, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/dolfinx/jit.py", line 206, in ffcx_jit
    r = ffcx.codegeneration.jit.compile_elements([ufl_object], parameters=p_ffcx, **p_jit)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/ffcx/codegeneration/jit.py", line 98, in compile_elements
    ffcx.naming.compute_signature(elements, _compute_parameter_signature(p)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/ffcx/naming.py", line 34, in compute_signature
    object_signature += repr(convert_element(ufl_object))
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/ffcx/element_interface.py", line 25, in convert_element
    return create_element(element)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/ffcx/element_interface.py", line 45, in create_element
    return basix.ufl_wrapper.TensorElement(create_element(element.sub_elements()[0]), element._value_shape)
  File "/home/armand/mambaforge/envs/dolfinx-stable/lib/python3.10/site-packages/basix/ufl_wrapper.py", line 1033, in __init__
    assert len(shape) == 2
AssertionError
```

dolfinx version is from latest conda update:
```shell
print(dolfinx.__version__)
0.5.0
```

The above MWE used to work in the previous conda version (0.4.2)

**Comment by francesco-ballarin** [comment] 2023-10-19 16:41
Can't reproduce anymore, this probably got fixed at some point between August 2022 and today.

```
import dolfinx.fem
import dolfinx.mesh
import mpi4py.MPI

mesh = dolfinx.mesh.create_unit_square(mpi4py.MPI.COMM_SELF, 3, 3)
gdim = mesh.geometry.dim
V = dolfinx.fem.functionspace(mesh, ("DG", 0, (gdim, gdim, gdim, gdim)))
print(V.ufl_element().value_shape)  # (2, 2, 2, 2)
```


if this is confirmed, @mscroggs may probably want to close this

**Closed** 2023-10-20 08:56 UTC
