### ISSUE TITLE
dolfinx linking with MPI_CXX

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#2229] opened 2022-06-05 11:47 UTC
PR #2116 replaced dolfinx's MPI linking from MPI::MPI_CXX to MPI::MPI_C.  But this generates a linking error, e.g. building cpp tests
```
...
[100%] Linking CXX executable unittests
/usr/bin/cmake -E cmake_link_script CMakeFiles/unittests.dir/link.txt --verbose=1
/usr/bin/c++ -g -O2 -ffile-prefix-map=/projects/fenics/build/fenics-dolfinx=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -pthread CMakeFiles/unittests.dir/main.cpp.o CMakeFiles/unittests.dir/poisson.c.o CMakeFiles/unittests.dir/vector.cpp.o CMakeFiles/unittests.dir/matrix.cpp.o CMakeFiles/unittests.dir/io.cpp.o CMakeFiles/unittests.dir/common/sub_systems_manager.cpp.o CMakeFiles/unittests.dir/common/index_map.cpp.o CMakeFiles/unittests.dir/common/sort.cpp.o CMakeFiles/unittests.dir/mesh/distributed_mesh.cpp.o CMakeFiles/unittests.dir/common/CIFailure.cpp.o -o unittests  -Wl,-rpath,/projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/openmpi/lib:/usr/lib/x86_64-linux-gnu/hdf5/openmpi:/usr/lib/slepcdir/slepc3.16/x86_64-linux-gnu-real/lib:/usr/lib/petscdir/petsc3.16/x86_64-linux-gnu-real/lib /projects/fenics/build/fenics-dolfinx/debian/tmp-real/usr/lib/x86_64-linux-gnu/libdolfinx_real.so.0.4.1 /usr/lib/x86_64-linux-gnu/libbasix.so.0.4.2 /usr/lib/x86_64-linux-gnu/libboost_timer.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.74.0 /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so /usr/lib/slepcdir/slepc3.16/x86_64-linux-gnu-real/lib/libslepc_real.so /usr/lib/petscdir/petsc3.16/x86_64-linux-gnu-real/lib/libpetsc_real.so 
/usr/bin/ld: CMakeFiles/unittests.dir/main.cpp.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Symbol _ZN3MPI8Datatype4FreeEv is used in libdolfinx.so, but is defined in libmpi_cxx.so, which isn't linked.

`mpicxx -show` indicates wrapper linking would proceed with `-lmpi_cxx -lmpi`. So as far as I can tell, cmake should be linking both MPI::MPI_CXX *and* MPI::MPI_C,

i.e. change cpp/dolfinx/CMakeLists.txt l.81 to
```
target_link_libraries(dolfinx PUBLIC MPI::MPI_CXX MPI::MPI_C)
```

This is with OpenMPI (and g++) on Debian linux, but `mpicxx.mpich -show` shows linking with `-lmpichcxx -lmpich`, so  MPICH would need it also.

**Comment by garth-wells** [comment] 2022-06-10 05:42
My suspicion is that this is a Debian bug. We don't use the MPI C++ interface, and the C++ interface was removed from MPI 3.0 (https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node405.htm#Node405).

**Comment by drew-parsons** [comment] 2022-06-10 07:34
Weird.  Perhaps we've done something strange peculiar with our libopenmpi.  I'll ask about.

**Comment by Armand-Touminet** [comment] 2022-06-10 14:16
I can reproduce the error using Archlinux. Both using the conda package or by building from source.
Can be fixed by setting `LD_PRELOAD` to point to the required `libmpi_cxx.so` file.

**Comment by garth-wells** [comment] 2022-06-10 16:39
Adding `MPI::MPI_CXX` (and removing `MPI::MPI_C`) might be ok since it seems it refers to the calling language and not the MPI C++ interface [1]. It probably parses `mpicxx`. 

@drew-parsons  Debian uses `--enable-mpi-cxx` [2] for OpenMPI, but C++ has been removed from the C++ standard. Why does Debian enable it?

[1] https://cmake.org/cmake/help/latest/module/FindMPI.html#variables-for-using-mpi
[2] https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=amd64&ver=4.1.4-1&stamp=1653824920&raw=0

**Comment by drew-parsons** [comment] 2022-06-10 17:39
> Debian uses `--enable-mpi-cxx` [2] for OpenMPI, but C++ has been removed from the C++ standard. Why does Debian enable it?

Couple of angles.  First, inertia.  If we used it in the past, and it's still working, then why remove it?  

Secondly, because we can.  Both OpenMPI and MPICH still provide the c++ variant, so we make it available.  In practice this would be the stronger reason  The distribution's job is to make the software available.  It's a different question why OpenMPI and MPICH still make it available if it's been removed from the standard.  If they stop supporting it then we won't be able to provide it.

The C++ interface (mpicxx.h) is included in mpi.h, but for OpenMPI it has comments relating it to MPI 2 C++ bindings support.  For the MPICH implementation there's so such caveat, they simply include mpicxx.h if MPICH_SKIP_MPICXX is not defined.

Possibly it's provided for applications that still need to use MPI 2.  Not sure why mpicxx would be assuming MPI-2 by default though. MPI-4 is already at hand.

**Closed** 2022-06-10 21:17 UTC

**Comment by carlosal1015** [comment] 2022-06-21 23:35
Hi @atouminet , [this workaround is not working anymore](https://aur.archlinux.org/packages/python-fenics-dolfinx#comment-863171) because [`libmpi_cxx.so` was deleted from openmpi in 4.1.4](https://archlinux.org/packages/extra/x86_64/openmpi/sonames).

I will try to fix the PKGBUILD soon.

**Comment by drew-parsons** [comment] 2022-06-22 00:07
Eh, I don't know what archlinux is doing, but it's stil in the debian package for openmpi 4.1.4, https://packages.debian.org/sid/amd64/libopenmpi3/filelist

**Comment by carlosal1015** [comment] 2022-06-22 00:22
Thanks, [tested python bindings](https://user-images.githubusercontent.com/21283014/174916947-6b1660e3-2ca4-47e4-9cfa-2ce08ed12d70.png) and [the updated PKGBUILD solved the issue on archlinux ](https://aur.archlinux.org/cgit/aur.git/commit/?h=dolfinx&id=755ee7fae317d5e6aedd084a858216926285055e). Yes, looks strange why is missing libmpi_cxx.so, but now the error _ZN3MPI8Datatype4FreeEv vanished.
