### ISSUE TITLE
[Unexpected Behavior]: Multiplying gradient with ScalarType leads to ValueError

### ISSUE THREAD

**Issue by Driy** [FEniCS/dolfinx#2923] opened 2023-12-05 18:03 UTC
### Summarize the issue

See example below, which fails when ScalarType(1) is inside ufl.dot(), but works when it is outside.

### How to reproduce the bug

I have attached a minimal example.

### Minimal Example (Python)

```Python
from mpi4py import MPI
from petsc4py.PETSc import ScalarType
import dolfinx
import ufl

mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 8, 8, dolfinx.mesh.CellType.quadrilateral)

P1 = ufl.FiniteElement("Lagrange", mesh.ufl_cell(), 1)
W  = dolfinx.fem.FunctionSpace(mesh, P1)
      
a = dolfinx.fem.Function(W)
ta = ufl.TestFunction(W)

ufl.dot(ScalarType(1)*ufl.grad(a),ufl.grad(ta))
```

### Output (Python)

```bash
ValueError: Invalid type conversion: [Indexed(Grad(Coefficient(FunctionSpace(Mesh(blocked element (Basix element (P, quadrilateral, 1, gll_warped, unset, False), (2,)), 6), FiniteElement('Q', quadrilateral, 1)), 6)), MultiIndex((FixedIndex(0),)))
 Indexed(Grad(Coefficient(FunctionSpace(Mesh(blocked element (Basix element (P, quadrilateral, 1, gll_warped, unset, False), (2,)), 6), FiniteElement('Q', quadrilateral, 1)), 6)), MultiIndex((FixedIndex(1),)))] can not be converted to any UFL type.
```

### Version

0.7.1

**Comment by francesco-ballarin** [comment] 2023-12-05 20:49
Updated code for `main`:

```
from mpi4py import MPI
from petsc4py.PETSc import ScalarType
import dolfinx
import ufl

mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 2, 2)

W  = dolfinx.fem.functionspace(mesh, ("Lagrange", 1))

a = ufl.TrialFunction(W)
ta = ufl.TestFunction(W)

one = dolfinx.fem.Constant(mesh, ScalarType(1.0))
correct = one*ufl.grad(a)
print("BEGIN CORRECT")
print(correct, type(correct))
print("END CORRECT")

one = ScalarType(1.0)
wrong = one*ufl.grad(a)
print("BEGIN WRONG")
print(wrong, type(wrong))
print("END WRONG")
```
prints
```
BEGIN CORRECT
{ A | A_{i_8} = c_0 * (grad(v_1))[i_8] } <class 'ufl.tensors.ComponentTensor'>
END CORRECT
BEGIN WRONG
[Indexed(Grad(Argument(FunctionSpace(Mesh(blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (2,)), 0), Basix element (P, triangle, 1, gll_warped, unset, False)), 1, None)), MultiIndex((FixedIndex(0),)))
 Indexed(Grad(Argument(FunctionSpace(Mesh(blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (2,)), 0), Basix element (P, triangle, 1, gll_warped, unset, False)), 1, None)), MultiIndex((FixedIndex(1),)))] <class 'numpy.ndarray'>
END WRONG
```

This because multiplying by a `np.float64` (i.e., `ScalarType` for a build with real numbers) converts the result into a `np.array`, rather than a `ufl` type. 
Overall, the issue is in `ufl`, not `dolfinx`. In the meantime, you can wrap your `ScalarType` in `dolfinx.fem.Constant`, as shown above.

**Comment by francesco-ballarin** [comment] 2023-12-09 08:38
Closing, because I don't think there is anything we can do here to allow
```
one = ScalarType(1.0)
wrong = one*ufl.grad(a)
```
to work. 

Indeed `help(numpy.float64)` shows

```
Help on class float64 in module numpy:

class float64(floating, builtins.float)
 |  float64(x=0, /)
....
 |  Methods defined here:
....
 |  __mul__(self, value, /)
 |      Return self*value.
```

and the order in which `__mul__` and `__rmul__` are queried is left object first (i.e., `one`, a `numpy.float64` object) and right object afterwards if querying the left object has failed, see
https://stackoverflow.com/questions/5181320/under-what-circumstances-are-rmul-called

Since `numpy.float64` has defined the policy that `numpy.float64.__mul__` that the return type gets changed to a `np.array`, there is no way for us to change that behavior in `ufl.Grad.__rmul__`.

Take home message: always wrap your `numpy.floating` types in a `dolfinx.fem.Constant`.

**Closed** 2023-12-09 08:38 UTC
Labels: bug
