### ISSUE TITLE
unsupported operand type(s) for *: 'FunctionSpace' and 'FunctionSpace'

### ISSUE THREAD

**Issue by iishiishii** [FEniCS/dolfinx#875] opened 2020-03-12 18:00 UTC
I tried to run this on both Google Colab and desktop environment but it always returned with a TypeError: unsupported operand type(s) for *: 'FunctionSpace' and 'FunctionSpace' 
ERROR:root:File '/home/fenics/fenics-matplotlib.py' not found.

```# Define function spaces and functions
Q = FunctionSpace(mesh, "CG", 1);
W = Q * Q;
h = CellSize(mesh);
(p, q) = TestFunctions(W); 
w = Function(W); 
(u, v) = (w[0], w[1]);
u0 = Function(Q); 
v0 = Function(Q);```

**Comment by francesco-ballarin** [comment] 2020-03-13 17:29
Hi,
from the declaration of the FunctionSpace I believe that you are referring to dolfin 2019.1.0, not dolfinx. In that case, you may want to have a look e.g. at
https://fenicsproject.org/docs/dolfin/latest/python/demos/mixed-poisson/demo_mixed-poisson.py.html
Note that the multiplication occurs between UFL elements, not function spaces.

In case you have further issues related to dolfin (and not dolfinx), you can use the issue tracker at https://bitbucket.org/fenics-project/dolfin/issues?status=new&status=open
You can also post general questions to the FEniCS discourse page at 
https://fenicsproject.discourse.group/

Please confirm that the issue is indeed related to dolfin (and not dolfinx), so that this can be closed by the project managers.

**Closed** 2020-03-13 17:55 UTC
