### ISSUE TITLE
Support uniform refinement of quadrilateral and hexahedral cell meshes

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#3489] opened 2024-10-29 13:15 UTC
Presently, uniform and local refinement of simplex cell meshes is support. There is no support for refinement of quadrilateral or hexahedral cell meshes.

Uniform refinement of quadrilateral/hexahedral cell meshes should be reasonably straightforward.

**Comment by jorgensd** [comment] 2024-10-29 13:20
Duplicate of: https://github.com/FEniCS/dolfinx/issues/3489

**Closed by jorgensd** 2024-10-29 13:20 UTC
Labels: enhancement

**Comment by jpdean** [comment] 2024-10-29 13:26
This is https://github.com/FEniCS/dolfinx/issues/3489... Guessing you meant https://github.com/FEniCS/dolfinx/issues/3006 😛
